/**
 * What each tree-sitter grammar calls the things a row or a facet asks about.
 * A list holds node types and a string holds a field name, which is how the
 * test checks every one of them against the vendored grammar.
 */
export const SHAPES = {
  python: {
    fn: ["function_definition"],
    cls: ["class_definition"],
    comment: ["comment"],
    catch: ["except_clause"],
    import: ["import_statement", "import_from_statement", "future_import_statement"],
    annotation: ["decorator"],
    wildcard: ["wildcard_import"],
    block: ["block"],
    noop: ["pass_statement"],
    docstring: ["expression_statement", "string", "concatenated_string"],
    tokensOf: [],
    name: "name",
    returnType: "return_type",
  },
  php: {
    fn: ["function_definition", "method_declaration"],
    cls: ["class_declaration", "interface_declaration", "trait_declaration", "enum_declaration"],
    comment: ["comment"],
    catch: ["catch_clause"],
    import: ["namespace_use_declaration"],
    annotation: ["attribute"],
    visibility: ["visibility_modifier"],
    block: ["compound_statement"],
    args: ["arguments"],
    call: ["function_call_expression"],
    // What a file holds outside any code: the tags, and the markup around them.
    header: ["php_tag", "text", "text_interpolation"],
    tokensOf: [],
    name: "name",
    returnType: "return_type",
    callee: "function",
  },
  go: {
    fn: ["function_declaration", "method_declaration"],
    // A Go method is written beside its type, so no body encloses one.
    cls: [],
    comment: ["comment"],
    catch: [],
    import: ["import_declaration"],
    annotation: [],
    header: ["package_clause"],
    tokensOf: [],
    name: "name",
  },
  java: {
    fn: ["method_declaration"],
    cls: ["class_declaration", "interface_declaration", "enum_declaration", "record_declaration", "annotation_type_declaration"],
    comment: ["line_comment", "block_comment"],
    catch: ["catch_clause"],
    import: ["import_declaration"],
    annotation: ["marker_annotation", "annotation"],
    wildcard: ["asterisk"],
    visibility: ["modifiers"],
    block: ["block"],
    args: ["annotation_argument_list"],
    header: ["package_declaration"],
    // `public` and `static` are tokens of `modifiers`, and its text is not kept once an annotation sits beside them.
    tokensOf: ["modifiers"],
    name: "name",
  },
  csharp: {
    fn: ["method_declaration", "local_function_statement"],
    cls: ["class_declaration", "interface_declaration", "struct_declaration", "record_declaration"],
    comment: ["comment"],
    catch: ["catch_clause"],
    import: ["using_directive"],
    annotation: ["attribute"],
    visibility: ["modifier"],
    block: ["block"],
    args: ["attribute_argument_list"],
    tokensOf: [],
    name: "name",
  },
  rust: {
    fn: ["function_item"],
    cls: ["impl_item", "trait_item"],
    comment: ["line_comment", "block_comment"],
    catch: [],
    import: ["use_declaration"],
    annotation: ["attribute_item", "inner_attribute_item"],
    wildcard: ["use_wildcard"],
    visibility: ["visibility_modifier"],
    doc: ["outer_doc_comment_marker"],
    args: ["token_tree"],
    mod: ["mod_item"],
    tokensOf: [],
    name: "name",
  },
  kotlin: {
    fn: ["function_declaration"],
    cls: ["class_declaration", "object_declaration", "companion_object"],
    comment: ["line_comment", "block_comment"],
    catch: ["catch_block"],
    import: ["import"],
    annotation: ["annotation"],
    visibility: ["visibility_modifier"],
    block: ["block"],
    args: ["value_arguments"],
    header: ["package_header"],
    // The `*` of `import a.b.*` is a token of `import` and nothing else marks a wildcard.
    tokensOf: ["import"],
    name: "name",
  },
};
